language: python
services:
- postgresql
python:
  - "3.6"
env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.test
    - DB=postgres 
    - DEBUG=False
    - DATABASE_URL=postgres://postgres@localhost/test_db
    - secure: "NQj/U2l3hORvZoHfFIYBwS9s7mOmrD1VgnmWZbAh6xmzUAzgZdsuaOhPhzbvUUyyBtepHmAGzuJgp63pd+fS7k1P5jT0EHRzGzf4JgwHCJ6ZUElWUfPIWooHTUcMawE1aSDhON7pQ+25KW8tCRNPGVTEEt/3HegbcopdugN3oe4vxAXNl0tnJeM+V2YNBrIfReZasqPyi3+Xl+LmKYBmr0uL0ko+UHN2V6jB3waKk2CWn26W2QfzFwmPStBzkx8rXMK0DC+QiyNII2m4Ydm0wDQX/vgRowmX0IRpbOJ7Zp1g8axXKnBvgtfh3cInSVuAaTcmSGJzFph7BtstgabyvX6l/LV8fNXuOWA3gX+nm8sT95HjUDRXL3U0gb/oSmoMC/A5v+9ioemTUvWyh/fpVrv1VyqqWfdu/XNkgS2Yn1+aFHSev+XUYMy0yBuTr3BP4+FPWNg/8WfTQ8tUPHdb9TRj0Fr7hsqqocWTQpxC/sZQmEFVpNaSqVIfW/uw2LFE8EbWTUuJYn+UJODp7uvr9im15wbaPgHMe48efCR691t+D03evPyDl0Z1x/YL77NGdjxT4zvN4qgFqruFzSiJ8xT83ufwv5+6B1VcHjxSBi9/lH40Xi3ApwbiqJXpCNewHiqEXJAFs146GMvKpYn2G1IrLhhvL3IbbK4OP0UxX48="
    - secure: "eFfcQKRaJovtfrYvvv+FdnfboRnq4tXaJ5U1y8tKcSIRBMhWH+Z+1Zf2FW/+Wz4GE6daBvQ9E2jGd14RAlXELmwD8yzMbJmD3+9uVbXzWZzNphB0GZ0jwREwxsRimMHL7UWTEViTsOQfVXRnJYhcKa2eNJdVkIyE9LZT7IRu3azAU8zZnGiKCrXgKVScpOvFh8HUZb+t2BpoLBWPThN8OPYISNrZCwDi6bKDdy8nrSsaNJsm/6rkTtJG2Fl0bykLkG+u0KM34DHIfcVQfNkH+X8xEUz4SA0HWAebX6FO3qVg4c8rI7eIpwa+volyPtxFedQN8Px+3sLuyqOJTVR8IoJVvTJouKQjYf5kbhb/e4JFIU4tmgM5Wl6X2N1Wms1n5OwkBkF5cw8vFjOD31BGkKzQN5e/UcKE7PXiwnwwv9g29VInF25cbzoTxQV+4LA+cF+WjRZE/mdr3ogfh1XXbNZ8wtuiqzhjwORM/W8qWr7mKR/n9OBfqbHhq1LHS9GO354CFwMxQgDd+GX9bgJ647EUW9yYtr4PtF1wy1gwiOCdb+5+brplhBLcjv61Qhl8WNOwdTYlo2qXE79xOwlMKslrWjYLwpteXhOTceDAjilmZYNjQBvvdQDaO09nmaZ7zwZtp8PGUpRi4rZVu7PfderVqPD17tWupDdY+BrqRG4="
    - secure: "R+p9/DsA9Wh5fft5y2RoI00722l1PukCnZY/7VGPRIoKf6L6+1Gqqi6hzc3dfIiRnyritKASZHFuctLoV9wMOTekHXDquCYbcB/A0pQ8z5AE+fLsLQNjfmYq2tnHi+FBrlWv3Vht0RUQVqZ4mSVjGLvjNYmnZasrQBQ2XJjkzOzfIAQmndI3fm6D5BFVWuBRkzTeaLvzQPoqNQGxxSYw9usBC+Fll8PAKgQS7ybFxtjS6dKXEbo/UjxrJKvfwn2z8JL3VH0IlpR63zstr2XpFUdoMenZyZc2jO2O72/UvejKVVo6iXseIhRTUMQaewTZ8Bi8KqE71ETwZ9w9f1JFeBFr/VI+SSyrIhlMiW8ed8cZ6bCPu1ZBs3GouK5re003OvWq3Bre1on3lyZ3U9Rg6jJvtNxUGD5iuNqhWEN3zJs8T2D67bZcqZy7Qqd0Sc+K7zMv+862fAcnt4tkpOwuQQgSUKY6McQFVMxj2KsGqhzRgxt50B1mEoTLcMK2EDnaGDBnF7y5dkm2o2RrUI6yXz1MFANsPMeZV6ns3BPmCAMFwA5di+RtSQhoJmG2ohKMfrX8EM9t4QU+93iiXDyTbZjvjlrTi73PSPLv20UOV+qslfEEK3mHmlYbw5pjCBI7AoBF7QQ+gwa3OfIJp3HVZrC1ydSxZ8pVvjKMlj9E8gw="
before_script:
  - psql -c 'create database test_db;' -U postgres
  - cd src 
  - python manage.py collectstatic
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python manage.py test