# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendPresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interest', models.DateTimeField(verbose_name='Date Interest')),
                ('confirmed', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.FloatField(default=0)),
                ('url', models.URLField(blank=True)),
                ('buyed', models.BooleanField(default=False)),
                ('date_buyed', models.DateTimeField(blank=True, verbose_name='Date Buyed')),
                ('date_inserted', models.DateTimeField(verbose_name='Date Inserted')),
                ('friendPresent', models.ManyToManyField(through='presents.FriendPresent', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='friendpresent',
            name='present',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presents.Present'),
        ),
    ]
