# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='date_buyed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Buyed'),
        ),
    ]
